### PR TITLE
feat(NSQ): 🎸 Add NSQ chart [INIM-880]

### PR DESCRIPTION
**Pull request by lucchmielowski**
Added NSQ Helm chart to repository

### CODE REVIEW

**Comment by RiceBowlJr** [comment]
Not super clean yet, we are working on making it work with our current NSQ deployed in staging and production.
But that's a first iteration.

**Comment by lucchmielowski** [comment]
@eddycharly @Atrax1 After all the PRs I have created and the fact that no-one seem to agree on the approach, I think I'll merge this one as it's the "best of both worlds" between putting everything in templates and everything in the main `/charts`. Any comment before I merge ?

**Comment by eddycharly** [comment]
Yeah, i still disagree with the approach. I don't understand the driver behind this choice and why we don't want to conform to good practices here.
You can merge if you want though, would be nice if you could explain what we gain/loose doing it this way.
I tried to give my points for a simpler approach, would be nice to have yours for this approach behind just "because we're used to do it this way".

**Comment by lucchmielowski** [comment]
@eddycharly I can give you my opinion here, I did not do it because "we've always done it that way". We choose to do it that way because the 3 parts are NOT the same app. As I explained previously NSQD is independent and can be used without the others 2 (same for NSQAdmin in a certain way). Since this is an OSS chart I believed we should not create this only for our own usage if we can (in this idea, I would prefer merging the PR with everything in `/charts` than this one)

Now if you tell me the good practice worldwide is to approach this kind of problem in a monolithic kind-of way and always put everything in `templates`, I don't mind create ONE LAST PR moving everything to templates and merging it.

**Comment by eddycharly** [comment]
They are the same app, the app is made of different components and those components can be enabled or disabled but i don't see anyone deploying `nsqlookupd` or `nsqadmin` on its own.

**Comment by lucchmielowski** [comment]
I guess you're right then, PR coming soon then !

**Pull request closed without merging**
