### PR TITLE
feat: add single NSQ chart

### PR DESCRIPTION
**Pull request by lucchmielowski**
# Description

Create an NSQ chart by putting everything under a single `/template` chart to comply with "Helm standards".

### CODE REVIEW

**Comment by eddycharly** [comment]
looks good to me !
in the end you didn't add flags for optional components ?

**Review by eddycharly — APPROVED** [review]

**Comment by lucchmielowski** [comment]
@eddycharly As you said before, who cares ? If someone needs to disable some components they can do a PR to add those flags right ?

**Comment by eddycharly** [comment]
> If someone needs to disable some components they can do a PR to add those flags right ?

Yeah, makes complete sense !

**Comment by eddycharly** [comment]
Good work ! It looks a lot better like this IMO ❤️

**Comment by lucchmielowski** [comment]
Screenshot 2020-12-14 at 12 37 43
I still don't like the fact that we have ~20 files in the repository and long `_helpers` / `values.yaml` files. But I guess I'll get over it 🤷

**Pull request merged**
