### PR TITLE
chore: Added NSQ dependency Charts

### PR DESCRIPTION
**Pull request by lucchmielowski**
# Description

Instead of putting everything `templates` we moved everything at the main level. There are some changes acccompanying this : 
- We will use `nsq`'s container params instead of using a shared configmap

I'm waiting for this PR to be merged to be able to create a meta chart with those charts as a requirement 👍  (I'm also pondering whether or not it's necessary TBH 🤔)

### CODE REVIEW

**Comment by eddycharly** [comment]
Au risque d’être relou pourquoi 3 charts ? Et un umbrella chart ?
Ça serait pas plus simple d’en avoir un seul ? Pour être sur qu’on release les bonnes versions qui vont bien ensemble, des trucs comme ça...
Et nsqd ne fonctionne pas sans nsqlookupd, comment tu réconcilier les 2 s’ils sont déployé séparément ? Je pense au service headless de nsqlookupd par exemple...

**Comment by lucchmielowski** [comment]
@eddycharly we went for 3 different chart for multiple reasons:
- Technically, those 2 of those 3 components are independent. For example, although it is recommended, you can use `nsqd`  without `nsqlookupd` (that's why you can find a lot of `nsqd` only charts). Same with nsqadmin, we could chose to get rid of it if we wanted.
- If by `umbrella` chart, you mean nested sub-charts. We already tried this approach with @RiceBowlJr and it's a bit painful to maintain with all the shared values that are supposed to be at the top level but that are also required by other components. Also, since Helm v3.4, it looks like we need to have `dependencies` even though they are local charts, we figured that at this point we might as well create 3 charts and a global `nsq` chart that will require those 3 ( i had planned to create a PR to add this last chart later since it'll depend on the other's URL as we don't really want to use `file://`)

As you said, configuration could be a bit painful with 3 separated charts and I'm trying to find a better way for people to write lookupd config. Without any change, I made it work on our agenda by doing : 

```yaml
# non-relevant config values were ommited

# workers
agendadDealerLookupd: "nsqlookupd-0.nsqlookupd.agenda:4161;nsqlookupd-1.nsqlookupd.agenda:4161;nsqlookupd-2.nsqlookupd.agenda:4161"

# nsq config
nsqadmin:
  args:
    - "-lookupd-http-address=nsqlookupd-0.nsqlookupd.agenda:4161"
    - "-lookupd-http-address=nsqlookupd-1.nsqlookupd.agenda:4161"
    - "-lookupd-http-address=nsqlookupd-2.nsqlookupd.agenda:4161"

nsqlookupd:
 replicaCount: 3

nsqd:
  args:
    - "-lookupd-tcp-address=nsqlookupd-0.nsqlookupd.agenda:4160"
    - "-lookupd-tcp-address=nsqlookupd-1.nsqlookupd.agenda:4160"
    - "-lookupd-tcp-address=nsqlookupd-2.nsqlookupd.agenda:4160"
```

Not sure if it's the best way to configure things with NSQ at all (maybe we could use a service instead), but I believe we could maybe use a global `.Values.global.nsqlookupd` object to help us share the data between the 3 elements.

By packaging everything under a single `nsq` chart I guess we could also try to have a cleaner configuration (using templates for example) but I believe in this specific the more explicit the configuration is, the better, since the workers will have kind-of the same URL as the nsqadmin worker 🤷

**Comment by eddycharly** [comment]
I’m definitely not convinced at all splitting into 3 charts is the right approach, doing it this way will lead to a solution full of limitations because those components are tightly coupled, you will have to shift all the configuration complexity at the end user side (he will have to provide endpoints one by one etc).

IMO a far better approach is to create a single chart and eventually make some components optional (with an enabled flag per component for example) this way the contract with the end user is about features not about technical configuration aspects and the configuration logic can be taken care of by the chart based on the end user requested features.
That’s what charts are used for. Look at other charts, redis doesn’t have one chart for masters and one chart for slaves, there’s one chart and you can enable or disable slaves. Same thing for postgresql, elasticsearch, etc....

To some extents, charts can have dependencies and those dependencies can come along with the chart but that should not be mandatory in all cases. Think about Argocd for example, when you deploy argocd the chart offers to deploy a redis, a redis ha, or you can bring your own redis. This is the correct approach as redis is not the Argo business but they need one to work. So they offer an option to deploy one automatically, that is great for most users, but at the same time they allow for extension and you can bring a redis that you created yourself with elasticache for example if you want. It follows the open/close principle (open for extension closed for modification).

Bref, a chart should package a product and allow for different setups that the user can configure for its needs. I don’t see the point in trying to make a responsible of a single binary.

**Comment by eddycharly** [comment]
Bottom line you want 2 statefulsets, 1 deployment, some storage, services fronting your workloads, and eventually some ingresses (ok, probably a few pdbs too).

I feel like you’re over engineering it, making it more complex than necessary, harder to maintain, harder to use, and addressing out of scope use cases.

**Comment by lucchmielowski** [comment]
Closed following discussion in #1

**Pull request closed without merging**
